### ISSUE TITLE
About Table 2

### ISSUE THREAD

**Issue by BeerTai** [svjan5/medtype#1]
Hi, thanks for your code! 
In the paper,  what is the difference between Oracle(F), Oracle(C), MedType in Table 2? 
Shouldn't MedType contain one of Oracle(F) and Oracle(C)?
Thanks~

**Comment by svjan5** [comment]
Hi @BeerTai,
Thanks for your interest in our work. 
Oracle (F) stands for Oracle with Fine-grained semantic types (that is using all 127 semantic type classes which are there in UMLS). Oracle (C) uses coarse-grained semantic types (we merge 127 into 24 semantic groups). 

Let me know if you have any other query.

**Comment by Zzzty843** [comment]
Hi, thanks for your code!
How does the pretrained model provided on GitHub work?
Thanks!
