### ISSUE TITLE
MedType Demo - not working

### ISSUE THREAD

**Issue by kswamy15** [svjan5/medtype#10]
When I go to your demo website, it asks me to accept the certificate in a popup and when I click Ok, takes me to https://128.2.204.127:8124/run_linker site but this site fails saying 'This site can't be reached'.  I have tried both Chrome and Edge.   I am not behind any proxy server.  I am trying from my home PC.

**Comment by kswamy15** [comment]
I tried using Postman as well but got the similar error.  Let me know if you are able to connect to the server.  

Could not get any response
There was an error connecting to https://128.2.204.127:8124/run_linker.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

**Comment by svjan5** [comment]
Hi @kswamy15, 
Sorry, it is not more being hosted. However, you can start your own demo. The code for that is available in the repo. 

thanks!

**Comment by runfish5** [comment]
I'm tying my own demo. I think it would be good to mention that the demo isn't working right now on the main page.
