### ISSUE TITLE
Semantic type/category information in PubMedDS and WikiMedDS datasets

### ISSUE THREAD

**Issue by gaurav** [svjan5/medtype#14]
Hi there!

I downloaded the datasets included with MedType by running [download_datasets.sh](https://github.com/svjan5/medtype/blob/6d31336525b57e8d7bb36f52039c68215d636a83/download_datasets.sh). I noticed that some datasets (`ncbi.json`, `medmentions.json`) include category information, while others (`wikimed.json`, `pubmed_ds`) don't. I couldn't find any documentation for why category information is not included -- I notice that figure 4 from [the MedType paper](https://dx.doi.org/10.1016/j.jbi.2021.103880) specifically mentions that Semantic Type of the term. Is that information available in these datasets somewhere? If so, could you please document how to access that information in this repository?

Thanks so much!

**Comment by svjan5** [comment]
Hi Gaurav, 
All the datasets are in the same format. Can you share an example from each dataset and what is missing in wikimed and pubmed_ds?

**Comment by gaurav** [comment]
Thanks for the quick response! I've set up a Gist showing what I mean at https://gist.github.com/gaurav/cbe44a3c3a36586d57fb9656c98bc2d9

If you look at an annotated entity C0013720 (Ehlers-Danlos syndrome) in MedMentions, you'll see that it includes the category (T047 = Disease or Syndrome):
https://gist.github.com/gaurav/cbe44a3c3a36586d57fb9656c98bc2d9#file-medmentions-line-70-json-L7-L13

However, a comparable annotated entity in PubMedDS includes a link_id (C00229045) and mesh_id (D009865), but no semantic type/category:
https://gist.github.com/gaurav/cbe44a3c3a36586d57fb9656c98bc2d9#file-pubmed-line-2-json-L6-L12

I think I can look up these categories by using PubMed's APIs, but since you mention it in your paper, I was wondering if maybe you had a version of PubMedDS that already included this category information? I think it might be of use to other users of PubMedDS as well.

Thanks again!

**Comment by svjan5** [comment]
Hi Gaurav, 
yes, seems like we somehow missed including that. Just use UMLS to get the semantic type for each concept.

thanks!
