### ISSUE TITLE
pretrained model URLs - `general text` and `Electronic Health Records (EHR)` same file?

### ISSUE THREAD

**Issue by kirrakula** [svjan5/medtype#3]
@svjan5 
Thanks for sharing.
Just wondering 
1. pretrained model URLs of `general text` and `Electronic Health Records` are linked to the same file? They are in different URLs but downloaded files are same size with same file name (`general_model.zip` 1185789292 bytes).
2. Online demo seems is not working for me (Linux 64 Chrome v.87 and Firefox v.78). Which browswers that you know are working?
Thanks

**Comment by svjan5** [comment]
Hi @kirrakula 
Thanks for pointing that out. I have updated all the models based on our new architecture. Please have a look. 
Our online demo is a bit unstable. You can try to run it locally on your system. 

Thanks!

**Comment by kirrakula** [comment]
Thanks!
