### ISSUE TITLE
Semantic type prediction results in paper

### ISSUE THREAD

**Issue by GanjinZero** [svjan5/medtype#5]
In table 5, you provide results of MT <- WikiMed & MT <- PubMedDS.
I am curious about the results of MedType trained on WikiMed(or PubMedDS) without fine-tuning in semantic type prediction.

**Comment by svjan5** [comment]
Hi @GanjinZero,
They do not give that great performance since the nature of training data and the evaluation data are quite different. However,  you do provide complementary information to the model which is not present in the training data.
