### ISSUE TITLE
Python package instead of medtype-as-service

### ISSUE THREAD

**Issue by vsocrates** [svjan5/medtype#6]
I think it'd be really helpful to pull out the entity linkers that are python libraries (all except for cTAKES) and make an python package to be used in notebooks and installed in conda/pip environments easily. 

I've made some changes and gotten the scispacy + medtype part to work without the server (if that's helpful), however I haven't checked the other linkers or done any extensive testing. Forked repo: https://github.com/vsocrates/medtype

**Comment by svjan5** [comment]
Thanks a lot, @vsocrates for your initiative. It sounds like a very good idea. Can you share an example showing how it can be used?

**Comment by vsocrates** [comment]
Yup, I spent some more time messing with the other entity linkers. It looks like MetaMap still needs a server to be running. but if it is installed according to the instructions in the main README.md and the two servers are started, my code seems to work. 

Here's some rough code that does the candidate filtering in a script. It still uses command line args for now, but can be easily changed and packaged into a library https://github.com/vsocrates/medtype/blob/641fe4651254823fc79d60ebe96b8ccb19f4121d/medtype-as-service/server/medtype_serving/server/testLinkage.py#L54

Also a notebook (ln 95, sorry for the gross outputs): https://github.com/vsocrates/medtype/blob/master/medtype-as-service/server/medtype_serving/server/note_exploration-medtype.ipynb

**Comment by svjan5** [comment]
Thanks a lot for your efforts! Please create a pull request for integrating your work in this repo. If it is hard to merge then you can consider mentioning your work in the README of this repository so that interested people can look at it. 

Thanks again!
