### ISSUE TITLE
UMLS authentication change

### ISSUE THREAD

**Issue by fhidalgor** [svjan5/medtype#8]
Hi,

One of your linkers (ctakes) has changed the way it connects to UMLS. I thought you would like to know so you update your Read.me

More info [here](https://cwiki.apache.org/confluence/display/CTAKES/cTAKES+4.0.0.1).

**Comment by svjan5** [comment]
Hi @fhidalgor,
Thanks for pointing that out.  If you know about the details then please create a pull request for indicating the required changes in the readme otherwise I will update as soon as possible.

Thanks!
