### ISSUE TITLE
Update entity_linkers.py

### ISSUE THREAD

**Issue by fhidalgor** [svjan5/medtype#9]
Hi,

There were problems when running scispacy linker v0.2. In particular, there was not a config.cfg file to read. I solved that by installing the v0.4.

However, in the new release there are a few changes with respect to nlp.add_pipe.
I had to manually change your source code file entity_linkers.py to make it run:
![image](https://user-images.githubusercontent.com/31396084/115942558-ab6fa080-a45f-11eb-98e2-d5107280aafa.png)

**Comment by svjan5** [comment]
Thanks for pointing that out!

**Comment by svjan5** [comment]
Please use the earlier version of scispacy to get it working out-of-the-box otherwise it would require a lot of non-trivial changes.
